server:
  port: 8086
  servlet:
    encoding:
      enabled: true
      force: true
      force-request: true
      force-response: true
      charset: utf-8
spring:
  application:
    name: ljp-eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8086/eureka/
logging:
  config: classpath:logback-spring.xml
  charset:
    console: utf-8
    file: UTF-8
  file:
    path: C:\\Users\\xhhm\\Desktop\\log
